server:
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-MICROSERVICE
        uri: lb://EMPLOYEE-MICROSERVICE
        predicates:
        - Path=/employee/**
      - id: DEPARTMENT-MICROSERVICE
        uri: lb://DEPARTMENT-MICROSERVICE
        predicates:
        - Path=/departments/** 

